### ISSUE TITLE
ValueError: Unknown layer: TrigPosEmbedding

### ISSUE THREAD

**Issue by yzho0907** [CyberZHG/keras-pos-embd#1]
Any idea how to fix it? there was no any problem during the training process but this error came out when i tried to load the model, thx!

**Comment by CyberZHG** [comment]
Remember to use custom objects:
https://github.com/CyberZHG/keras-pos-embd/blob/15b14e4a264334c49da8882c733bed637c4540cd/tests/test_trig_pos_embd.py#L40

**Comment by yzho0907** [comment]
@CyberZHG thx, that's right
