### ISSUE TITLE
维度不一致，相加报错

### ISSUE THREAD

**Issue by xugaoliang** [CyberZHG/keras-pos-embd#5]
add模式下，多个不同维度的输入，共用一个PositionEmbedding时，将会报错。因为相加时，PositionEmbedding的维度不可能既满足第一个输入的加法，又满足第二个输入的加法。

或许133行可以改为
inputs + pos_embeddings[:,:,:output_dim]
或者
把129行第二个self去掉
但改129行应该会影响其他模式

小白飘过，看大神怎么改法

**Comment by CyberZHG** [comment]
不同维度输入没必要共用embedding吧。

**Comment by xugaoliang** [comment]
我在处理金融数据，每个时刻可以有价格，交易量，交易次数等多种特征，他们有共同的时刻信息，所以感觉共用一个位置嵌入矩阵更合适


| |
徐高亮
|
|
邮箱：08oucxgl@163.com
|

签名由 网易邮箱大师 定制

在2019年10月29日 13:31，Zhao HG 写道：

不同维度输入没必要共用embedding吧。
